test

diff --git a/.github/workflows/backend_test.yaml b/.github/workflows/backend_test.yaml
--- a/.github/workflows/backend_test.yaml
+++ b/.github/workflows/backend_test.yaml
@@ -29,58 +29,58 @@ jobs:
           distribution: temurin
           cache: gradle
   
-  admin:
-    runs-on: ubuntu-latest
-    needs: setup
-    defaults:
-      run:
-        shell: bash
-        working-directory: backend
-    steps:
-      - name: Run AdminApi Tests
-        run: ./gradlew :adapters:adminApi:test --stacktrace --no-daemon --build-cache
-        env:
-          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-          DB_URL: ${{ secrets.DB_URL }}
-          DB_USER: ${{ secrets.DB_USER }}
-          GOOGLE_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
-          JWT_ENCRYPTION_KEY: ${{ secrets.JWT_ENCRYPTION_KEY }}
-          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
-          REDIS_ENDPOINT: ${{ secrets.REDIS_ENDPOINT }}
-          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
-          SESSION_SIGN_KEY: ${{ secrets.SESSION_SIGN_KEY }}
+  # admin:
+  #   runs-on: ubuntu-latest
+  #   needs: setup
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: backend
+  #   steps:
+  #     - name: Run AdminApi Tests
+  #       run: ./gradlew :adapters:adminApi:test --stacktrace --no-daemon --build-cache
+  #       env:
+  #         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+  #         DB_URL: ${{ secrets.DB_URL }}
+  #         DB_USER: ${{ secrets.DB_USER }}
+  #         GOOGLE_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
+  #         JWT_ENCRYPTION_KEY: ${{ secrets.JWT_ENCRYPTION_KEY }}
+  #         JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
+  #         REDIS_ENDPOINT: ${{ secrets.REDIS_ENDPOINT }}
+  #         SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
+  #         SESSION_SIGN_KEY: ${{ secrets.SESSION_SIGN_KEY }}
 
-  blog:
-    runs-on: ubuntu-latest
-    needs: setup
-    defaults:
-      run:
-        shell: bash
-        working-directory: backend
-    steps:
-      - name: Run BlogApi Tests
-        run: ./gradlew :adapters:blogApi:test --stacktrace --no-daemon --build-cache
-        env:
-          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-          DB_URL: ${{ secrets.DB_URL }}
-          DB_USER: ${{ secrets.DB_USER }}
+  # blog:
+  #   runs-on: ubuntu-latest
+  #   needs: setup
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: backend
+  #   steps:
+  #     - name: Run BlogApi Tests
+  #       run: ./gradlew :adapters:blogApi:test --stacktrace --no-daemon --build-cache
+  #       env:
+  #         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+  #         DB_URL: ${{ secrets.DB_URL }}
+  #         DB_USER: ${{ secrets.DB_USER }}
 
-  core:
-    runs-on: ubuntu-latest
-    needs: setup
-    defaults:
-      run:
-        shell: bash
-        working-directory: backend
-    steps:
-      - name: Run Core Tests
-        run: ./gradlew :core:test --stacktrace --no-daemon --build-cache
+  # core:
+  #   runs-on: ubuntu-latest
+  #   needs: setup
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: backend
+  #   steps:
+  #     - name: Run Core Tests
+  #       run: ./gradlew :core:test --stacktrace --no-daemon --build-cache
 
-  reports:
-    if: success() || failure() # always run even if the previous step fails
-    needs: [setup, admin, blog, core]
-    steps:
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v3
-        with:
-          report_paths: '**/build/test-results/test/TEST-*.xml'
+  # reports:
+  #   if: success() || failure() # always run even if the previous step fails
+  #   needs: [setup, admin, blog, core]
+  #   steps:
+  #     - name: Publish Test Report
+  #       uses: mikepenz/action-junit-report@v3
+  #       with:
+  #         report_paths: '**/build/test-results/test/TEST-*.xml'
