add post test ci

diff --git a/.github/workflows/backend_test.yaml b/.github/workflows/backend_test.yaml
--- a/.github/workflows/backend_test.yaml
+++ b/.github/workflows/backend_test.yaml
@@ -6,7 +6,7 @@ on:
       - 'backend/**'
 
 jobs:
-  test:
+  setup:
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -28,8 +28,16 @@ jobs:
           java-version: 17
           distribution: temurin
           cache: gradle
-
-      - name: Run Backend Tests
+  
+  admin:
+    runs-on: ubuntu-latest
+    needs: setup
+    defaults:
+      run:
+        shell: bash
+        working-directory: backend
+    steps:
+      - name: Run AdminApi Tests
         run: ./gradlew :adapters:adminApi:test --stacktrace --no-daemon --build-cache
         env:
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
@@ -42,8 +50,37 @@ jobs:
           SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
           SESSION_SIGN_KEY: ${{ secrets.SESSION_SIGN_KEY }}
 
+  blog:
+    runs-on: ubuntu-latest
+    needs: setup
+    defaults:
+      run:
+        shell: bash
+        working-directory: backend
+    steps:
+      - name: Run BlogApi Tests
+        run: ./gradlew :adapters:blogApi:test --stacktrace --no-daemon --build-cache
+        env:
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+          DB_URL: ${{ secrets.DB_URL }}
+          DB_USER: ${{ secrets.DB_USER }}
+
+  core:
+    runs-on: ubuntu-latest
+    needs: setup
+    defaults:
+      run:
+        shell: bash
+        working-directory: backend
+    steps:
+      - name: Run Core Tests
+        run: ./gradlew :core:test --stacktrace --no-daemon --build-cache
+
+  reports:
+    if: success() || failure() # always run even if the previous step fails
+    needs: [setup, admin, blog, core]
+    steps:
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v3
-        if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: '**/build/test-results/test/TEST-*.xml'
